### PR TITLE
Adding Keylogger

### PR DESCRIPTION
**Pull request by Debang5hu**
It is a simple but effective keylogger made in python,works well in LAN!

### CODE REVIEW

**Comment by kurogai** [comment]
Please change the folder name to match the repo requirementes
Looks good!!

**Comment by Debang5hu** [comment]
I have changed the name according to the requirements,but their are no specific ID for keylogger,I have used the ID 0 since the keylogger use basic TCP server for sending the Keystrokes.

**Comment by kurogai** [comment]
Indeed, didn't saw that
In this case, please change the id to "x" since this project is not listed on the repo, i'll make changes later

**Comment by Debang5hu** [comment]
Done!

**Comment by kurogai** [comment]
Looks good, thanks!

**Pull request merged**
